# Generated by Django 5.2.1 on 2025-07-02 17:57

import posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag_post_source_url_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='document',
            field=models.FileField(blank=True, help_text='Upload documents (PDF, DOC, DOCX, PPT, PPTX, XLS, XLSX). Max size: 50MB', null=True, upload_to='comment_documents/', validators=[posts.validators.validate_document_file]),
        ),
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, help_text='Upload documents (PDF, DOC, DOCX, PPT, PPTX, XLS, XLSX). Max size: 50MB', null=True, upload_to='post_documents/', validators=[posts.validators.validate_document_file]),
        ),
    ]
