# Generated by Django 5.2.1 on 2025-07-02 19:35

import django.db.models.deletion
import posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_document_post_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='document',
        ),
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='CommentAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(help_text='Upload audio files (MP3, WAV, OGG, M4A, AAC, FLAC, WMA, OPUS, WEBM). Max size: 50MB', upload_to='comment_audios/', validators=[posts.validators.validate_audio_file])),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='posts.comment')),
            ],
        ),
        migrations.CreateModel(
            name='CommentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Upload documents (PDF, DOC, DOCX, PPT, PPTX, XLS, XLSX). Max size: 50MB', upload_to='comment_documents/', validators=[posts.validators.validate_document_file])),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='posts.comment')),
            ],
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload images (JPG, JPEG, PNG, GIF, BMP, WEBP, SVG, TIFF). Max size: 50MB', upload_to='comment_images/', validators=[posts.validators.validate_image_file])),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.comment')),
            ],
        ),
        migrations.CreateModel(
            name='CommentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Upload videos (MP4, AVI, MOV, WMV, FLV, WEBM, MKV, M4V, 3GP, OGV). Max size: 50MB', upload_to='comment_videos/', validators=[posts.validators.validate_video_file])),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='posts.comment')),
            ],
        ),
        migrations.CreateModel(
            name='PostAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(help_text='Upload audio files (MP3, WAV, OGG, M4A, AAC, FLAC, WMA, OPUS, WEBM). Max size: 50MB', upload_to='post_audios/', validators=[posts.validators.validate_audio_file])),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Upload documents (PDF, DOC, DOCX, PPT, PPTX, XLS, XLSX). Max size: 50MB', upload_to='post_documents/', validators=[posts.validators.validate_document_file])),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload images (JPG, JPEG, PNG, GIF, BMP, WEBP, SVG, TIFF). Max size: 50MB', upload_to='post_images/', validators=[posts.validators.validate_image_file])),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Upload videos (MP4, AVI, MOV, WMV, FLV, WEBM, MKV, M4V, 3GP, OGV). Max size: 50MB', upload_to='post_videos/', validators=[posts.validators.validate_video_file])),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='posts.post')),
            ],
        ),
    ]
