# Generated by Django 5.2.1 on 2025-06-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='created_at',
        ),
    ]
