# Generated by Django 5.2.1 on 2025-06-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_achievement_achievement_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathonachievement',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='hackathonachievement',
            name='technologies_used',
        ),
        migrations.RemoveField(
            model_name='internshipachievement',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='internshipachievement',
            name='technologies_used',
        ),
        migrations.AddField(
            model_name='achievement',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prize/stipend amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in days (for events/internships)', null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository', null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='mentor_name',
            field=models.CharField(blank=True, help_text='Mentor name (for internships)', max_length=100),
        ),
        migrations.AddField(
            model_name='achievement',
            name='prize_position',
            field=models.CharField(choices=[('winner', 'Winner/1st Place'), ('runner_up', 'Runner Up/2nd Place'), ('third', '3rd Place'), ('finalist', 'Finalist'), ('participant', 'Participant'), ('special_award', 'Special Award'), ('completion', 'Completion Certificate'), ('not_applicable', 'Not Applicable')], default='not_applicable', help_text='Position/award received (for competitions/hackathons)', max_length=20),
        ),
        migrations.AddField(
            model_name='achievement',
            name='project_title',
            field=models.CharField(blank=True, help_text='Project/work title (for hackathons/internships)', max_length=200),
        ),
        migrations.AddField(
            model_name='achievement',
            name='project_url',
            field=models.URLField(blank=True, help_text='Project demo URL', null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='rank',
            field=models.PositiveIntegerField(blank=True, help_text='Your rank/position (for competitions)', null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='team_members',
            field=models.TextField(blank=True, help_text='Team member names (comma separated)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='technologies_used',
            field=models.ManyToManyField(blank=True, help_text='Technologies/skills used or learned', related_name='achievements', to='users.skill'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='total_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Total participants (for competitions)', null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('award', 'Award/Recognition'), ('certification', 'Certification'), ('competition', 'Competition/Contest'), ('hackathon', 'Hackathon'), ('internship', 'Internship/Fellowship'), ('scholarship', 'Scholarship'), ('volunteer', 'Volunteer Recognition'), ('sports', 'Sports/Tournament'), ('other', 'Other')], default='award', max_length=20),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='url',
            field=models.URLField(blank=True, help_text='Link to certificate/publication/event page', null=True),
        ),
        migrations.DeleteModel(
            name='CompetitiveAchievement',
        ),
        migrations.DeleteModel(
            name='HackathonAchievement',
        ),
        migrations.DeleteModel(
            name='InternshipAchievement',
        ),
    ]
