# Generated by Django 5.2.1 on 2025-06-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_profile_memory_usermemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(default='award', max_length=32),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, help_text='Type of degree', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(default='personal', max_length=32),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='experience_type',
            field=models.CharField(default='job', max_length=32),
        ),
    ]
