# Generated by Django 5.2.1 on 2025-06-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_drop_specialized_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='associated_institution',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='mentor_name',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='prize_position',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='project_url',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='technologies_used',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='total_participants',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='associated_institution',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='citations',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='journal_conference',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='pdf_url',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('award', 'Award/Recognition'), ('certification', 'Certification'), ('competition', 'Competition/Contest'), ('hackathon', 'Hackathon'), ('internship', 'Internship/Fellowship'), ('scholarship', 'Scholarship'), ('other', 'Other')], default='award', max_length=20),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='issuer',
            field=models.CharField(help_text='Organization that issued this', max_length=200),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='url',
            field=models.URLField(blank=True, help_text='Link to certificate or details', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(help_text='All authors (comma separated)', max_length=500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('journal', 'Journal Paper'), ('conference', 'Conference Paper'), ('thesis', 'Thesis/Dissertation'), ('book', 'Book/Chapter'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True, help_text='Link to publication', null=True),
        ),
    ]
