# Generated by Django 5.2.1 on 2025-06-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_simplify_achievement_publication_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the publication'),
        ),
    ]
