# Generated by Django 5.2.1 on 2025-06-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='users_embedding',
        ),
    ]
