# Generated by Django 5.2.1 on 2025-06-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_description_to_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='institution',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='start_year',
        ),
        migrations.AddField(
            model_name='institution',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank if currently studying', null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
