# Generated by Django 5.2.1 on 2025-06-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_change_institution_to_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='company_name',
            new_name='wroks_at',
        ),
    ]
