# Generated by Django 5.2.1 on 2025-06-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_company_name_workexperience_wroks_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='wroks_at',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='users.workorganization'),
        ),
    ]
