# Generated by Django 5.2.1 on 2025-06-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_workorganization_remove_workexperience_wroks_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_memory',
            field=models.TextField(blank=True, help_text="A memory of the user's interactions with LLM for cross-conversation context", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_summary',
            field=models.TextField(blank=True, help_text="A brief summary of the user's profile generated by LLM", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='users_embedding',
            field=models.TextField(blank=True, help_text="The user's profile embedding for recommendations generated by LLM", null=True),
        ),
    ]
