# Generated by Django 5.2.1 on 2025-06-06 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_convert_skill_interest_to_manytomany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={},
        ),
        migrations.RemoveField(
            model_name='institution',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='start_date',
        ),
        migrations.AddField(
            model_name='institution',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(help_text='Field of study/Major', max_length=200)),
                ('degree', models.CharField(choices=[('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate/PhD'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('other', 'Other')], help_text='Type of degree', max_length=20)),
                ('series', models.CharField(blank=True, help_text="Series/Batch (e.g., 'Fall 2020', '21st Batch')", max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently studying', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Currently studying here')),
                ('description', models.TextField(blank=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.institution')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.profile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
