# Generated by Django 5.2.1 on 2025-06-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_education_degree_alter_education_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the user first joined', null=True),
        ),
    ]
