# Generated by Django 5.2.1 on 2025-06-06 20:55

from django.db import migrations
from django.utils import timezone


def populate_created_at(apps, schema_editor):
    """Set created_at for existing profiles to current datetime"""
    Profile = apps.get_model("users", "Profile")
    current_time = timezone.now()

    # Update all profiles that have null created_at
    Profile.objects.filter(created_at__isnull=True).update(created_at=current_time)


def reverse_populate_created_at(apps, schema_editor):
    """Reverse operation - set created_at back to null"""
    Profile = apps.get_model("users", "Profile")
    Profile.objects.all().update(created_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_profile_created_at"),
    ]

    operations = [
        migrations.RunPython(populate_created_at, reverse_populate_created_at),
    ]
